[package]
name = "visual_compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ebnf = { git = "https://github.com/ChAoSUnItY/ebnf", version = "0.1.2" }
tera = "1"
once_cell = "1.16.0"
